version: '3'
services:
  db:
    image: "postgres"
    restart: unless-stopped
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/postgresql/data/
  bot:
    image: docker.io/fnecas/greyabot
    restart: unless-stopped
    volumes:
      - ./config.json:/config.json
    ports:
      -  "127.0.0.1:8080:8080"
      - "40000:40000"
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    depends_on:
      - db

volumes:
  database-data:
